/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddImageComponent: typeof import('./src/components/AddImageComponent.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AlertComponent: typeof import('./src/components/AlertComponent.vue')['default']
    Arlet: typeof import('./src/components/Arlet.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    ComboBoxComponent: typeof import('./src/components/ComboBoxComponent.vue')['default']
    InformationBook1: typeof import('./src/components/InformationBook1.vue')['default']
    InformationBook2: typeof import('./src/components/InformationBook2.vue')['default']
    InformationBook3: typeof import('./src/components/InformationBook3.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent.vue')['default']
    ItemAdminComponent: typeof import('./src/components/ItemAdminComponent.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PublicationYearComponent: typeof import('./src/components/PublicationYearComponent.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIAdminComponent: typeof import('./src/components/UIAdminComponent.vue')['default']
    UserCardComponent: typeof import('./src/components/UserCardComponent.vue')['default']
  }
}
