/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AddBookPage': RouteRecordInfo<'/AddBookPage', '/AddBookPage', Record<never, never>, Record<never, never>>,
    '/AuthFormComponent': RouteRecordInfo<'/AuthFormComponent', '/AuthFormComponent', Record<never, never>, Record<never, never>>,
    '/EditBookPage': RouteRecordInfo<'/EditBookPage', '/EditBookPage', Record<never, never>, Record<never, never>>,
    '/InfoBook': RouteRecordInfo<'/InfoBook', '/InfoBook', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/ManageBookPage': RouteRecordInfo<'/ManageBookPage', '/ManageBookPage', Record<never, never>, Record<never, never>>,
    '/RegisterPage': RouteRecordInfo<'/RegisterPage', '/RegisterPage', Record<never, never>, Record<never, never>>,
    '/SearchBook': RouteRecordInfo<'/SearchBook', '/SearchBook', Record<never, never>, Record<never, never>>,
  }
}
